export const AuditAction = {
  USER_LOGIN: 'USER_LOGIN',
  USER_LOGIN_FAILED: 'USER_LOGIN_FAILED',
  USER_LOGOUT: 'USER_LOGOUT',
  USER_REGISTERED: 'USER_REGISTERED',
  USER_CREATED: 'USER_CREATED',
  USER_UPDATED: 'USER_UPDATED',
  REFRESH_TOKEN_REUSED: 'REFRESH_TOKEN_REUSED',
  HOSPITAL_CREATED: 'HOSPITAL_CREATED',
  HOSPITAL_UPDATED: 'HOSPITAL_UPDATED',
  PATIENT_REGISTERED: 'PATIENT_REGISTERED',
  PATIENT_UPDATED: 'PATIENT_UPDATED',
  PATIENT_ACCESSED: 'PATIENT_ACCESSED',
} as const;

export type AuditActionType = (typeof AuditAction)[keyof typeof AuditAction];
