export const AuditAction = {
  USER_LOGIN: 'USER_LOGIN',
  USER_LOGIN_FAILED: 'USER_LOGIN_FAILED',
  USER_LOGOUT: 'USER_LOGOUT',
  USER_REGISTERED: 'USER_REGISTERED',
  USER_CREATED: 'USER_CREATED',
  USER_UPDATED: 'USER_UPDATED',
  REFRESH_TOKEN_REUSED: 'REFRESH_TOKEN_REUSED',
  HOSPITAL_CREATED: 'HOSPITAL_CREATED',
  HOSPITAL_UPDATED: 'HOSPITAL_UPDATED',
  PATIENT_REGISTERED: 'PATIENT_REGISTERED',
  PATIENT_UPDATED: 'PATIENT_UPDATED',
  PATIENT_ACCESSED: 'PATIENT_ACCESSED',

  DEPARTMENT_CREATED: 'DEPARTMENT_CREATED',
  DEPARTMENT_UPDATED: 'DEPARTMENT_UPDATED',

  DOCTOR_CREATED: 'DOCTOR_CREATED',
  DOCTOR_UPDATED: 'DOCTOR_UPDATED',
  DOCTOR_DEACTIVATED: 'DOCTOR_DEACTIVATED',
  DOCTOR_SCHEDULE_CREATED: 'DOCTOR_SCHEDULE_CREATED',
  DOCTOR_SCHEDULE_UPDATED: 'DOCTOR_SCHEDULE_UPDATED',
  DOCTOR_UNAVAILABILITY_CREATED: 'DOCTOR_UNAVAILABILITY_CREATED',

  APPOINTMENT_CREATED: 'APPOINTMENT_CREATED',
  APPOINTMENT_UPDATED: 'APPOINTMENT_UPDATED',
  APPOINTMENT_CANCELLED: 'APPOINTMENT_CANCELLED',
  APPOINTMENT_RESCHEDULED: 'APPOINTMENT_RESCHEDULED',
  APPOINTMENT_NO_SHOW: 'APPOINTMENT_NO_SHOW',
  APPOINTMENT_COMPLETED: 'APPOINTMENT_COMPLETED',

  QUEUE_ENTRY_CREATED: 'QUEUE_ENTRY_CREATED',
  QUEUE_ENTRY_CALLED: 'QUEUE_ENTRY_CALLED',
  QUEUE_ENTRY_SKIPPED: 'QUEUE_ENTRY_SKIPPED',
  QUEUE_ENTRY_STARTED: 'QUEUE_ENTRY_STARTED',
  QUEUE_ENTRY_COMPLETED: 'QUEUE_ENTRY_COMPLETED',
  QUEUE_ENTRY_CANCELLED: 'QUEUE_ENTRY_CANCELLED',
} as const;

export type AuditActionType = (typeof AuditAction)[keyof typeof AuditAction];
